name: 'Zeebe Action'
description: 'A GitHub action to interact with Zeebe and Camunda Cloud'
author: 'Josh Wulf'
branding:
  icon: 'upload-cloud'  
  color: 'orange'
inputs:
  operation: # change this
    required: true
    description: 'The operation to perform. One of publishMessage | createWorkflowInstance | createWorkflowInstanceWithResult | deployWorkflow'
  message_name: 
    required: false
    description: "The name of the message for a publishMessage operation"
  variables: 
    required: false
    description: "The stringified JSON of the variables for the operation"
    default: "{}"
  correlationKey:
    required: false
    description: "The correlationKey for a publishMessage operation"
  timeToLive: 
    required: false
    description: "The timeToLive for the message sent by a publishMessage operation"
  bpmn_filename:
    required: false
    description: "The bpmn file to deploy"
  bpmn_directory:
    required: false
    description: "A directory from which to deploy bpmn files"
  bpmnProcessId:
    required: false
    description: "The id of the process definition for a createWorkflowInstance operation"
  request_timeout:
    required: false
    description: "The requestTimeout for a createWorkflowInstanceWithResult operation"
  zeebe_address: 
    required: false
    description: "The ZEEBE_ADDRESS from your Camunda Cloud client credentials"
  zeebe_client_id: 
    required: false
    description: "The ZEEBE_CLIENT_ID from your Camunda Cloud client credentials"
  zeebe_client_secret: 
    required: false
    description: "The ZEEBE_CLIENT_SECRET from your Camunda Cloud client credentials"
  client_config:
    required: false
    description: "The client credentials for Camunda Cloud"
outputs:
  result: # id of the output
    description: 'The JSON stringified response from the operation, if a createWorkflow operation'

runs:
  using: 'node12'
  main: 'dist/index.js'
